name: Functional tests 

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python: ["3.11"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Install Scoop
        run: |
          Set-ExecutionPolicy RemoteSigned -scope CurrentUser
          Start-Process powershell -Verb RunAs -ArgumentList '-NoProfile -ExecutionPolicy Bypass -Command "iex (new-object net.webclient).downloadstring(''https://get.scoop.sh'')"' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
       
      - name: Build
        shell: pwsh
        run: scoop install allure

      - name: Test with pytest
        run: pytest -v tests   

      - name: Save Allure Result
        run: pytest --alluredir=allure_results

      - name: Genereta Allure Report
        run: allure generate allure_results -o allure_report


